<?php

namespace LGP\ReservationBundle\Repository;

/**
 * JourDeCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourDeCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
