<?php

namespace LGP\ReservationBundle\Repository;

/**
 * ReservationEnseignementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationEnseignementRepository extends \Doctrine\ORM\EntityRepository
{
}
