<?php

namespace LGP\CourseBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository {

    public function getCategorieByIntitule($intitule) {
        $query = $this->_em->createQuery("SELECT c FROM LGPCourseBundle:Categorie c WHERE c.intitule LIKE :intitule");
        $query->setParameter("intitule", $intitule . "%");
        $query->getSingleResult();

//        $query = $this->createQueryBuilder('c')
//                ->where('c.intitule = :intitule')
//                ->setParameter('intitule', $intitule);
//        
//        $query->getQuery()->getResult();
    }

    public function countProfByCategory($category) {
        $query = $this->_em->createQuery("SELECT c FROM LGPCourseBundle:Cours c WHERE c.intitule LIKE :intitule");
        $query->setParameter("intitule", $intitule . "%");
        $query->getSingleResult();
    }

    public function getAllCategories($page = 1, $max = 10) {
        $query = $this->createQueryBuilder('c')
                ->select('c')
                ->setFirstResult(($page - 1) * $max)
                ->setMaxResults($max);
        $paginator = new Paginator($query);
        return $paginator;
    }

}
