<?php

namespace LGP\CourseBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategorieByIntitule($intitule){
        $query = $this->_em->createQuery("SELECT c FROM LGPCourseBundle:Categorie c WHERE c.intitule LIKE :intitule");
        $query->setParameter("intitule", $intitule."%");
        $query->getSingleResult();
        
//        $query = $this->createQueryBuilder('c')
//                ->where('c.intitule = :intitule')
//                ->setParameter('intitule', $intitule);
//        
//        $query->getQuery()->getResult();
                
    }
}
