<?php

namespace LGP\CourseBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends EntityRepository {

    public function getAllCoursesByCategory($cat, $page = 1, $max = 10) {
        $query = $this->_em->createQuery('SELECT c FROM LGPCourseBundle:Cours c WHERE c.categorie = :categorie');
        $query->setParameter('categorie', $cat)
                ->setFirstResult(($page - 1) * $max)
                ->setMaxResults($max);
        
        return new Paginator($query);
    }

}
