<?php

namespace LGP\CourseBundle\Repository;

/**
 * EnseigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseigneRepository extends \Doctrine\ORM\EntityRepository {

    public function getProfsByCours($id) {
        
        $query = $this->_em->createQuery("SELECT DISTINCT e, p FROM LGPCourseBundle:Enseigne e JOIN e.prof p WHERE e.cours = :cours GROUP BY p.id");

        $query->setParameter('cours', $id);

        return $query->getResult();
    }

}
