<?php

namespace LGP\CourseBundle\Repository;

/**
 * EnseigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseigneRepository extends \Doctrine\ORM\EntityRepository {

    public function getProfsByCours($cours) {

        $query = $this->_em->createQuery("SELECT DISTINCT e, p FROM LGPCourseBundle:Enseigne e JOIN e.prof p WHERE e.cours = :cours GROUP BY p.id");

        $query->setParameter('cours', $cours);

        return $query->getResult();
    }

    public function getCoursByProf($prof) {
        $query = $this->_em->createQuery("SELECT DISTINCT e, c FROM LGPCourseBundle:Enseigne e JOIN e.cours c WHERE e.prof = :prof GROUP BY c.id");

        $query->setParameter('prof', $prof);
//        $query->setMaxResults(2);

        return $query->getResult();
    }

}
