<?php

namespace LGP\CourseBundle\Repository;

/**
 * EntreeProgrammeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreeProgrammeRepository extends \Doctrine\ORM\EntityRepository
{
}
