<?php

namespace LGP\CourseBundle\Repository;

/**
 * ImageCourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageCourseRepository extends \Doctrine\ORM\EntityRepository
{
}
