<?php

namespace LGP\CourseBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
