<?php

namespace LGP\CourseBundle\Repository;

/**
 * ProgrammeDeCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammeDeCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
