<?php

namespace LGP\CourseBundle\Repository;

/**
 * SeanceDeCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceDeCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
