services:
# Admin

#    User
    lgp.admin.user:
        class: LGP\AdminBundle\Admin\User\UserAdmin
        arguments: [~, LGP\UserBundle\Entity\User, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Utilisateurs

    lgp.admin.prof:
        class: LGP\AdminBundle\Admin\User\ProfAdmin
        arguments: [~, LGP\UserBundle\Entity\Prof, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Profs

    lgp.admin.parent:
        class: LGP\AdminBundle\Admin\User\ParentsAdmin
        arguments: [~, LGP\UserBundle\Entity\Parents, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Parents

    lgp.admin.remuneration:
        class: LGP\AdminBundle\Admin\User\RemunerationAdmin
        arguments: [~, LGP\UserBundle\Entity\Remuneration, LGPAdminBundle:RemunerationCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Rémunérations

    lgp.admin.quartier_cible:
            class: LGP\AdminBundle\Admin\User\QuartierAdmin
            arguments: [~, LGP\UserBundle\Entity\Quartier, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  label: Quartiers dans lesquels les profs peuvent donner cours

    lgp.admin.message:
            class: LGP\AdminBundle\Admin\User\MessageAdmin
            arguments: [~, LGP\UserBundle\Entity\Message, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  label: Messages

    lgp.admin.jour_dispo:
            class: LGP\AdminBundle\Admin\User\JourDispoAdmin
            arguments: [~, LGP\UserBundle\Entity\JourDispo, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  label: Jours de disponibilité

    lgp.admin.horaire:
            class: LGP\AdminBundle\Admin\User\HoraireAdmin
            arguments: [~, LGP\UserBundle\Entity\Horaire, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  label: Horaires de disponibilité des profs

    lgp.admin.indisponibilite:
            class: LGP\AdminBundle\Admin\User\IndisponibiliteAdmin
            arguments: [~, LGP\UserBundle\Entity\Indisponibilite, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  label: Indisponibilités

    lgp.admin.anomalie:
            class: LGP\AdminBundle\Admin\User\AnomalieAdmin
            arguments: [~, LGP\UserBundle\Entity\Anomalie, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  label: Anomalies du système

    lgp.admin.avis:
            class: LGP\AdminBundle\Admin\User\AvisAdmin
            arguments: [~, LGP\UserBundle\Entity\Avis, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  label: Avis des utilisateurs

    lgp.admin.cvfile:
            class: LGP\AdminBundle\Admin\User\CVFileAdmin
            arguments: [~, LGP\UserBundle\Entity\CVFile, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  label: CV des profs

    lgp.admin.diplome:
            class: LGP\AdminBundle\Admin\User\DiplomeAdmin
            arguments: [~, LGP\UserBundle\Entity\Diplome, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  label: Diplômes des profs

    lgp.admin.experiencepro:
            class: LGP\AdminBundle\Admin\User\ExperienceProAdmin
            arguments: [~, LGP\UserBundle\Entity\ExperiencePro, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  label: Expériences professionnelles des profs

    lgp.admin.imageprofil:
            class: LGP\AdminBundle\Admin\User\ImageAdmin
            arguments: [~, LGP\UserBundle\Entity\Image, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  label: Images de profil des utilisateurs

    lgp.admin.nouvellecategoriecours:
            class: LGP\AdminBundle\Admin\User\NouvelleCategorieCoursAdmin
            arguments: [~, LGP\UserBundle\Entity\NouvelleCategorieCours, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  label: Catégories de cours proposées

# Reservation
    lgp.admin.reservation:
        class: LGP\AdminBundle\Admin\Reservation\ReservationAdmin
        arguments: [~, LGP\ReservationBundle\Entity\Reservation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Réservations


    lgp.admin.jourdecours:
        class: LGP\AdminBundle\Admin\Reservation\JourDeCoursAdmin
        arguments: [~, LGP\ReservationBundle\Entity\JourDeCours, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Jours de cours

    lgp.admin.reservationenseignement:
        class: LGP\AdminBundle\Admin\Reservation\ReservationEnseignementAdmin
        arguments: [~, LGP\ReservationBundle\Entity\ReservationEnseignement, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Réservations enseignements

    lgp.admin.paiement:
        class: LGP\AdminBundle\Admin\Reservation\PaiementAdmin
        arguments: [~, LGP\ReservationBundle\Entity\Paiement, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Paiements de factures

    lgp.admin.facture:
        class: LGP\AdminBundle\Admin\Reservation\FactureAdmin
        arguments: [~, LGP\ReservationBundle\Entity\Facture, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Factures


# Cours
    lgp.admin.categorie_cours:
        class: LGP\AdminBundle\Admin\Course\CategorieAdmin
        arguments: [~, LGP\CourseBundle\Entity\Categorie, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Catégories cours

    lgp.admin.cours:
        class: LGP\AdminBundle\Admin\Course\CourseAdmin
        arguments: [~, LGP\CourseBundle\Entity\Cours, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Cours

    lgp.admin.enseignement:
        class: LGP\AdminBundle\Admin\Course\EnseignementAdmin
        arguments: [~, LGP\CourseBundle\Entity\Enseignement, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Enseignements

    lgp.admin.programmedecours:
        class: LGP\AdminBundle\Admin\Course\ProgrammeDeCoursAdmin
        arguments: [~, LGP\CourseBundle\Entity\ProgrammeDeCours, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Programmes de cours

    lgp.admin.entreeprogramme:
        class: LGP\AdminBundle\Admin\Course\EntreeProgrammeAdmin
        arguments: [~, LGP\CourseBundle\Entity\EntreeProgramme, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Entrées des programmes de cours

    lgp.admin.evaluation:
        class: LGP\AdminBundle\Admin\Course\EvaluationAdmin
        arguments: [~, LGP\CourseBundle\Entity\Evaluation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Evaluations

    lgp.admin.seancedecours:
        class: LGP\AdminBundle\Admin\Course\SeanceDeCoursAdmin
        arguments: [~, LGP\CourseBundle\Entity\SeanceDeCours, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Séances de cours
