lgp_course_category:
    path:     /category
    defaults: { _controller: LGPCourseBundle:Course:allCategories }

lgp_course_find_prof:
    path:     /search/prof/{matiere}
    defaults: { _controller: LGPCourseBundle:Course:search }
    
lgp_course_find_category:
    path:     /search/{category}
    defaults: { _controller: LGPCourseBundle:Course:category }
