lgp_course_all_intitule:
    path:     /all/intitule
    defaults: { _controller: LGPCourseBundle:Course:updateCourseData}
    options: 
        expose: true

# categories
lgp_course_categories:
    path:     /categories/{page}
    defaults: { _controller: LGPCourseBundle:Categorie:index, page: 1 }
    requirements:
        page:   \d+


lgp_course_find_category:
    path:     /search/categories/{slug}/{page}
    defaults: { _controller: LGPCourseBundle:Categorie:courseList, page: 1 }
    requirements:
        page:   \d+


# course
lgp_course_find:
    path:     /search/profs/{page}
    defaults: { _controller: LGPCourseBundle:Course:search, page: 1 }
    requirements:
        page:   \d+

    
lgp_course_find_prof:
    path:     /search/profs/{slug}/{page}
    defaults: { _controller: LGPCourseBundle:Course:searchCourse, page: 1 }
    requirements:
        page:   \d+


lgp_course_find_prof_refine:
    path:     /search/profs/{slugVille}/{slug}/{page}
    defaults: { _controller: LGPCourseBundle:Course:searchRefine, page: 1 }
    requirements:
        page:   \d+

lgp_course_find_prof_refine_quarter:
    path:     /search/profs/{slug_ville}/{slug_quartier}/{slug}/{page}
    defaults: { _controller: LGPCourseBundle:Course:searchRefineAll, page: 1 }
    requirements:
        page:   \d+

lgp_course_find_prof_update_quarter:
    path:     /search/update/{ville}
    defaults: { _controller: LGPCourseBundle:Course:updateQuarter}
    options:
        expose: true
    methods: [POST]

lgp_course_find_prof_city:
    path:     search/ville/{slugVille}/{page}
    defaults: { _controller: LGPCourseBundle:Course:searchCity, page: 1 }
    requirements:
        page:   \d+

lgp_course_find_prof_city_quarter:
    path:     search/ville/{slug_ville}/quartier/{slug_quartier}/{page}
    defaults: { _controller: LGPCourseBundle:Course:searchCityQuarter, page: 1 }
    requirements:
        page:   \d+

lgp_course_update_classe:
    path:     update/{profId}/{coursId}
    defaults: { _controller: LGPCourseBundle:Course:updateClasse }
    requirements:
        profId:   \d+
        coursId: \d+
    methods: [POST]
    options:
        expose: true
        
# enseignement
lgp_course_profile_prof:
    path:     /profile/{slug}
    defaults: { _controller: LGPCourseBundle:Enseignement:profile}
