lgp_course_category:
    path:     /categories/{page}
    defaults: { _controller: LGPCourseBundle:Course:allCategories, page: 1 }
    requirements:
        page:   \d+


lgp_course_find_category:
    path:     /search/categories/{category}/{page}
    defaults: { _controller: LGPCourseBundle:Course:category, page: 1 }
    requirements:
        page:   \d+


  
lgp_course_find:
    path:     /search/profs/{page}
    defaults: { _controller: LGPCourseBundle:Course:search, page: 1 }
    requirements:
        page:   \d+

    
lgp_course_find_prof:
    path:     /search/profs/{intitule_cours}/{page}
    defaults: { _controller: LGPCourseBundle:Course:searchCourse, page: 1 }
    requirements:
        page:   \d+


lgp_course_find_prof_refine:
    path:     /search/profs/{ville}/{intitule_cours}/{page}
    defaults: { _controller: LGPCourseBundle:Course:searchRefine, page: 1 }
    requirements:
        page:   \d+


lgp_course_find_prof_city:
    path:     search/ville/{ville}/{page}
    defaults: { _controller: LGPCourseBundle:Course:searchCity, page: 1 }
    requirements:
        page:   \d+

lgp_course_update_classe:
    path:     update/{profId}/{coursId}
    defaults: { _controller: LGPCourseBundle:Course:updateClasse }
    requirements:
        profId:   \d+
        coursId: \d+
        method: POST
    options:
        expose: true

  