services:
#    lgp_course.example:
#        class: LGP\CourseBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    lgp.course.form.course.search:
        class: LGP\CourseBundle\Form\CoursSearchType
        arguments: []
