lgp_core_homepage:
    path:     /
    defaults: { _controller: LGPCoreBundle:Lgp:index }
    
lgp_core_how_it_works:
    path:    /how-it-works
    defaults: { _controller: LGPCoreBundle:Lgp:how }

lgp_core_contact:
    path:    /contact
    defaults: { _controller: LGPCoreBundle:Lgp:contact }
    
