lgp_reservation:
    resource: "@LGPReservationBundle/Resources/config/routing.yml"
    prefix:   /reservation

lgp_course:
    resource: "@LGPCourseBundle/Resources/config/routing.yml" 
    prefix:   /course

lgp_core:
    resource: "@LGPCoreBundle/Resources/config/routing.yml"
    prefix:   /

