lgp_user:
    resource: "@LGPUserBundle/Resources/config/routing.yml"
    prefix:   /user
    
lgp_reservation:
    resource: "@LGPReservationBundle/Resources/config/routing.yml"
    prefix:   /reservation

lgp_course:
    resource: "@LGPCourseBundle/Resources/config/routing.yml"
    prefix:   /course

lgp_core:
    resource: "@LGPCoreBundle/Resources/config/routing.yml"
    prefix:   /

# FOSUserBundle
fos_user_security:
    resource: "@LGPUserBundle/Resources/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
   
# Sonata
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
