# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    lgp.form.registration:
        class: LGPUserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: lgp_user_registration }

# Admin
    lgp.admin.prof:
        class: LGP\AdminBundle\Admin\User\ProfAdmin
        arguments: [~, LGP\UserBundle\Entity\Prof, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Profs

    lgp.admin.parent:
        class: LGP\AdminBundle\Admin\User\ParentsAdmin
        arguments: [~, LGP\UserBundle\Entity\Parents, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Parents

    lgp.admin.remuneration:
        class: LGP\AdminBundle\Admin\Reservation\RemunerationAdmin
        arguments: [~, LGP\UserBundle\Entity\Remuneration, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Rémunérations

    lgp.admin.quartier_cible:
        class: LGP\AdminBundle\Admin\User\QuartierAdmin
        arguments: [~, LGP\UserBundle\Entity\Quartier, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Quartiers cibles

    lgp.admin.categorie_cours:
        class: LGP\AdminBundle\Admin\Course\CategorieAdmin
        arguments: [~, LGP\CourseBundle\Entity\Categorie, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Catégories cours

    lgp.admin.cours:
        class: LGP\AdminBundle\Admin\Course\CourseAdmin
        arguments: [~, LGP\CourseBundle\Entity\Cours, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Cours
