# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    lgp.form.registration:
        class: LGPUserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: lgp_user_registration }


    lgp.admin.prof:
        class: LGP\AdminBundle\Admin\ProfAdmin
        arguments: [~, LGP\UserBundle\Entity\Prof, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Prof

    lgp.admin.remuneration:
        class: LGP\AdminBundle\Admin\RemunerationAdmin
        arguments: [~, LGP\UserBundle\Entity\Remuneration, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Rémunération