<?php

namespace LGP\UserBundle\Repository;

/**
 * AnomalieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnomalieRepository extends \Doctrine\ORM\EntityRepository
{
}
