<?php

namespace LGP\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends EntityRepository {

    public function getAvis($prof, $limit) {
        $query = $this->_em->createQuery('SELECT a FROM LGPUserBundle:Avis a JOIN a.prof p WHERE p = :prof');
        $query->setParameter('prof', $prof)
                ->setMaxResults($limit);
        return new Paginator($query);
    }

}
