<?php

namespace LGP\UserBundle\Repository;

/**
 * CVFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CVFileRepository extends \Doctrine\ORM\EntityRepository
{
}
