<?php

namespace LGP\UserBundle\Repository;

/**
 * DiplomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiplomeRepository extends \Doctrine\ORM\EntityRepository
{
  public function getByProf($id) {
    $qb = $this->_em->createQuery(
      'SELECT d.id, d.intitule, d.fileName FROM LGPUserBundle:Diplome d JOIN d.prof p WHERE p.id = :id'
    );
    
    $qb->setParameter('id', $id);
    
    return $qb->getResult();
  }
}
