<?php

namespace LGP\UserBundle\Repository;

/**
 * ExperienceProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceProRepository extends \Doctrine\ORM\EntityRepository
{
  public function getByProf($id)
  {
    $qb = $this->_em->createQuery(
      'SELECT e.id, e.etablissement, e.poste, e.dateDebut, e.dateFin FROM LGPUserBundle:ExperiencePro e JOIN e.prof p WHERE p.id = :id'
    );
    
    $qb->setParameter('id', $id);
    
    return $qb->getResult();
  }
}
