<?php

namespace LGP\UserBundle\Repository;

/**
 * ExperienceProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceProRepository extends \Doctrine\ORM\EntityRepository
{
}
