<?php

namespace LGP\UserBundle\Repository;

/**
 * filePDFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class filePDFRepository extends \Doctrine\ORM\EntityRepository
{
}
