<?php

namespace LGP\UserBundle\Repository;

/**
 * IndisponibiliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndisponibiliteRepository extends \Doctrine\ORM\EntityRepository
{
}
