<?php

namespace LGP\UserBundle\Repository;

/**
 * JourDispoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourDispoRepository extends \Doctrine\ORM\EntityRepository
{
}
