<?php

namespace LGP\UserBundle\Repository;

/**
 * NouvelleCategorieCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NouvelleCategorieCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
