<?php

namespace LGP\UserBundle\Repository;

/**
 * ProfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfRepository extends \Doctrine\ORM\EntityRepository
{
  public function getProf($id)
  {
    $query = $this->_em->createQuery("SELECT p, u FROM LGPUserBundle:Prof p JOIN p.user u WHERE u.id = :id");

    $query->setParameter('id', $id);

    return $query->getSingleResult();
  }
}
