<?php

namespace LGP\UserBundle\Repository;

/**
 * ProgrammeDeDispoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammeDeDispoRepository extends \Doctrine\ORM\EntityRepository
{
}
