lgp_user_homepage:
    path:     /
    defaults: { _controller: LGPUserBundle:Main:index }
    
# Registration
lgp_parent_registration:
    path:  /register/parent
    defaults: { _controller: LGPUserBundle:RegistrationParent:register }

lgp_prof_registration:
    path:  /register/prof
    defaults: { _controller: LGPUserBundle:RegistrationProf:register }

# Dashboard
lgp_user_dashboard:
    path: /dashboard
    defaults: { _controller: LGPUserBundle:Dashboard:index }
    
# Avis
lgp_user_avis_add:
    path: /avis/add
    defaults: { _controller: LGPUserBundle:Avis:add }
    
lgp_user_avis_voir:
    path: /avis/voir/{id}
    defaults: { _controller: LGPUserBundle:Avis:voir }
    requirements:
      id: \d+
    
lgp_user_avis_delete:
    path: /avis/delete/{id}
    defaults: { _controller: LGPUserBundle:Avis:delete }
    requirements:
      id: \d+
    
lgp_user_avis_update:
    path: /avis/update/{id}
    defaults: { _controller: LGPUserBundle:Avis:update }
    requirements:
      id: \d+
    
lgp_user_avis:
    path: /avis
    defaults: { _controller: LGPUserBundle:Avis:index }
    options:
        expose: true
    
# Indisponibilite
lgp_user_prof_indisponibilite:
    path: /prof/indisponibilite
    defaults: { _controller: LGPUserBundle:Indisponibilite:index }
    
lgp_user_prof_indisponibilite_add:
    path: /prof/indisponibilite/add
    defaults: { _controller: LGPUserBundle:Indisponibilite:add }
    
lgp_user_prof_indisponibilite_update:
    path: /prof/indisponibilite/update/{id}
    defaults: { _controller: LGPUserBundle:Indisponibilite:update }
    requirements: 
      id: \d+
    
lgp_user_prof_indisponibilite_delete:
    path: /prof/indisponibilite/delete/{id}
    defaults: { _controller: LGPUserBundle:Indisponibilite:delete }
    requirements:
      id: \d+
      
# Messages
lgp_user_message_send:
    path: /messages/send
    defaults: { _controller: LGPUserBundle:Message:send }
    
lgp_user_message_receive:
    path: /messages/receive
    defaults: { _controller: LGPUserBundle:Message:receive }
    options:
        expose: true
    
lgp_user_message_new:
    path: /message/new
    defaults: { _controller: LGPUserBundle:Message:new }

lgp_user_message_delete:
    path: /message/delete/{id}
    defaults: { _controller: LGPUserBundle:Message:delete }
    requirements:
      id: \d+

lgp_user_message_voir:
    path: /message/{id}
    defaults: { _controller: LGPUserBundle:Message:voir }
    requirements:
      id: \d+
      
# Cours
lgp_user_prof_cours:
    path: /prof/cours
    defaults: { _controller: LGPUserBundle:Cours:index }  
    
lgp_user_prof_cours_add:
    path: /prof/cours/add
    defaults: { _controller: LGPUserBundle:Cours:add }  

lgp_user_prof_cours_update:
    path: /prof/cours/update/{id}
    defaults: { _controller: LGPUserBundle:Cours:update }  
    requirements:
      id: \d+
    
lgp_user_prof_cours_delete:
    path: /prof/cours/delete/{id}
    defaults: { _controller: LGPUserBundle:Cours:delete }  
    requirements:
      id: \d+
      
# Evaluation
lgp_user_prof_evaluation:
    path: /prof/evaluations
    defaults: { _controller: LGPUserBundle:Evaluation:index } 
    
lgp_user_prof_evaluation_add:
    path: /prof/evaluations/add
    defaults: { _controller: LGPUserBundle:Evaluation:add }  
    
lgp_user_prof_evaluation_update:
    path: /prof/evaluations/update/{id}
    defaults: { _controller: LGPUserBundle:Evaluation:update }
    requirements:
      id: \d+
    
lgp_user_prof_evaluation_delete:
    path: /prof/evaluations/delete/{id}
    defaults: { _controller: LGPUserBundle:Evaluation:delete }  
    requirements:
      id: \d+
      
# SeanceDeCours
lgp_user_prof_seance_de_cours:
    path: /prof/seance-de-cours/
    defaults: { _controller: LGPUserBundle:SeanceDeCours:index }  
 
lgp_user_prof_seance_de_cours_add:
    path: /prof/seance-de-cours/add
    defaults: { _controller: LGPUserBundle:SeanceDeCours:add }  

lgp_user_prof_seance_de_cours_delete:
    path: /prof/seance-de-cours/delete/{id}
    defaults: { _controller: LGPUserBundle:SeanceDeCours:delete }  
    requirements:
      id: \d+
      
lgp_user_prof_seance_de_cours_update:
    path: /prof/seance-de-cours/update/{id}
    defaults: { _controller: LGPUserBundle:SeanceDeCours:update }  
    requirements:
      id: \d+
      
# Anomalie
lgp_user_anomalies:
    path: /anomalies
    defaults: { _controller: LGPUserBundle:Anomalie:index }  

lgp_user_anomalie_add:
    path: /anomalie/add
    defaults: { _controller: LGPUserBundle:Anomalie:add }  
    
# Anomalie
lgp_user_prof_nouvelles_categories_cours:
    path: /nouvelles-categories-cours
    defaults: { _controller: LGPUserBundle:NouvelleCategorieCours:index }  

lgp_user_prof_nouvelle_categorie_cours_add:
    path: /nouvelle-categorie-cours/add
    defaults: { _controller: LGPUserBundle:NouvelleCategorieCours:add }  