lgp_user_homepage:
    path:     /users
    defaults: { _controller: LGPUserBundle:Main:index }
    options:
        expose: true
    
# Registration
lgp_parent_registration:
    path:  /register/parent
    defaults: { _controller: LGPUserBundle:RegistrationParent:register }
    
lgp_prof_registration:
    path:  /register/prof
    defaults: { _controller: LGPUserBundle:RegistrationProf:register }
    
lgp_prof_registration_step1:
    path:  /register/prof/step1
    defaults: { _controller: LGPUserBundle:RegistrationProf:step1 }

lgp_prof_registration_step2:
    path:  /register/prof/step2
    defaults: { _controller: LGPUserBundle:RegistrationProf:step2 }
    
lgp_prof_registration_step3:
    path:  /register/prof/step3
    defaults: { _controller: LGPUserBundle:RegistrationProf:step3 }
    
# Dashboard
lgp_user_prof_dashboard:
    path: /prof/dashboard
    defaults: { _controller: LGPUserBundle:Dashboard:prof }

lgp_user_parent_dashboard:
    path: /parent/dashboard
    defaults: { _controller: LGPUserBundle:Dashboard:parent }
    
# Avis
lgp_user_avis_add:
    path: /avis/add
    defaults: { _controller: LGPUserBundle:Avis:add }
    
lgp_user_avis_voir:
    path: /avis/voir/{id}
    defaults: { _controller: LGPUserBundle:Avis:voir }
    requirements:
      id: \d+
    
lgp_user_avis_delete:
    path: /avis/delete/{id}
    defaults: { _controller: LGPUserBundle:Avis:delete }
    requirements:
      id: \d+
    
lgp_user_avis_update:
    path: /avis/update/{id}
    defaults: { _controller: LGPUserBundle:Avis:update }
    requirements:
      id: \d+
    
lgp_user_avis:
    path: /avis
    defaults: { _controller: LGPUserBundle:Avis:index }
    options:
        expose: true
    
# Indisponibilite
lgp_user_prof_indisponibilite:
    path: /prof/indisponibilite
    defaults: { _controller: LGPUserBundle:Indisponibilite:index }
    
lgp_user_prof_indisponibilite_add:
    path: /prof/indisponibilite/add
    defaults: { _controller: LGPUserBundle:Indisponibilite:add }
    
lgp_user_prof_indisponibilite_update:
    path: /prof/indisponibilite/update/{id}
    defaults: { _controller: LGPUserBundle:Indisponibilite:update }
    requirements: 
      id: \d+
    
lgp_user_prof_indisponibilite_delete:
    path: /prof/indisponibilite/delete/{id}
    defaults: { _controller: LGPUserBundle:Indisponibilite:delete }
    requirements:
      id: \d+
      
# Messages
lgp_user_message_send:
    path: /messages/send
    defaults: { _controller: LGPUserBundle:Message:send }
    
lgp_user_message_receive:
    path: /messages/receive
    defaults: { _controller: LGPUserBundle:Message:receive }
    options:
        expose: true
    
lgp_user_message_new:
    path: /message/new
    defaults: { _controller: LGPUserBundle:Message:new }

lgp_user_message_delete:
    path: /message/delete/{id}
    defaults: { _controller: LGPUserBundle:Message:delete }
    requirements:
      id: \d+

lgp_user_message_voir:
    path: /message/{id}
    defaults: { _controller: LGPUserBundle:Message:voir }
    requirements:
      id: \d+
      
# Cours
lgp_user_prof_cours:
    path: /prof/cours
    defaults: { _controller: LGPUserBundle:Cours:index }  
    
lgp_user_prof_cours_add:
    path: /prof/cours/add
    defaults: { _controller: LGPUserBundle:Cours:add }  

lgp_user_prof_cours_update:
    path: /prof/cours/update/{id}
    defaults: { _controller: LGPUserBundle:Cours:update }  
    requirements:
      id: \d+
    
lgp_user_prof_cours_delete:
    path: /prof/cours/delete/{id}
    defaults: { _controller: LGPUserBundle:Cours:delete }  
    requirements:
      id: \d+
      
# Evaluation
lgp_user_prof_evaluation:
    path: /prof/evaluations
    defaults: { _controller: LGPUserBundle:Evaluation:index }
    
lgp_user_prof_evaluation_delete:
    path: /prof/evaluations/delete/{id}
    defaults: { _controller: LGPUserBundle:Evaluation:delete }  
    requirements:
      id: \d+
      
# SeanceDeCours
lgp_user_prof_seance_de_cours:
    path: /prof/seance-de-cours/
    defaults: { _controller: LGPUserBundle:SeanceDeCours:index }  

lgp_user_prof_seance_de_cours_delete:
    path: /prof/seance-de-cours/delete/{id}
    defaults: { _controller: LGPUserBundle:SeanceDeCours:delete }  
    requirements:
      id: \d+
      
# Anomalie
lgp_user_anomalies:
    path: /anomalies
    defaults: { _controller: LGPUserBundle:Anomalie:index }  

lgp_user_anomalie_add:
    path: /anomalie/add
    defaults: { _controller: LGPUserBundle:Anomalie:add }  

lgp_user_anomalie_update:
    path: /anomalie/update/{id}
    defaults: { _controller: LGPUserBundle:Anomalie:update }  
    requirements:
        id: \d+

lgp_user_anomalie_delete:
    path: /anomalie/delete/{id}
    defaults: { _controller: LGPUserBundle:Anomalie:delete } 
    requirements:
        id: \d+
    
# NouvelleCategorieCours
lgp_user_nouvelles_categories_cours:
    path: /nouvelles-categories-cours
    defaults: { _controller: LGPUserBundle:NouvelleCategorieCours:index }  

lgp_user_nouvelle_categorie_cours_add:
    path: /nouvelle-categorie-cours/add
    defaults: { _controller: LGPUserBundle:NouvelleCategorieCours:add }  

lgp_user_nouvelle_categorie_cours_update:
    path: /nouvelle-categorie-cours/update/{id}
    defaults: { _controller: LGPUserBundle:NouvelleCategorieCours:update } 
    requirements:
        id: \d+

lgp_user_nouvelle_categorie_cours_delete:
    path: /nouvelle-categorie-cours/delete/{id}
    defaults: { _controller: LGPUserBundle:NouvelleCategorieCours:delete } 
    requirements:
        id: \d+
        
# Reservation
lgp_user_mes_reservations:
    path: /mes-reservations
    defaults: { _controller: LGPUserBundle:Reservation:index }

lgp_user_programme_et_jours_de_cours_voir:
    path: /reservation-enseignement/{id}/programme-et-jours-de-cours
    defaults: { _controller: LGPUserBundle:Reservation:showProgrammeAndJoursDeCours }
    requirements:
        id: \d+
    
# Demandes de cours
lgp_user_prof_demandes_de_cours:
    path: /prof/mes-demandes-de-cours
    defaults: { _controller: LGPUserBundle:MesDemandesDeCours:index }

lgp_user_prof_demande_de_cours_edit:
    path: /prof/demande-de-cours/edit/{id}
    defaults: { _controller: LGPUserBundle:MesDemandesDeCours:edit }
    requirements:
        id: \d+

# Paiement
lgp_user_mes_paiements:
    path: /mes-paiements
    defaults: { _controller: LGPUserBundle:Paiement:index }

lgp_user_programme_et_jours_de_cours_voir:
    path: /reservation-enseignement/{id}/programme-et-jours-de-cours
    defaults: { _controller: LGPUserBundle:Reservation:showProgrammeAndJoursDeCours }
    requirements:
        id: \d+

# Heures de disponibilites
lpg_user_prof_disponibilite:
    path: /disponibilites
    defaults: { _controller: LGPUserBundle:Disponibilite:index }

lpg_user_prof_disponibilite_edit:
    path: /disponibilites/edit
    defaults: { _controller: LGPUserBundle:Disponibilite:edit }

lpg_user_prof_disponibilite_add:
    path: /disponibilites/add
    defaults: { _controller: LGPUserBundle:Disponibilite:add }

#    Quartier dans lesquels les profs peuvent donner cours
lgp_user_prof_quartier_add:
    path: /quartier/add
    defaults: { _controller: LGPUserBundle:Quartier:add }
    options:
        expose: true

lgp_user_prof_quartier_delete:
    path: /quartier/delete/{id}
    defaults: { _controller: LGPUserBundle:Quartier:delete }
    requirements:
        id: \d+
    options:
        expose: true

lgp_user_prof_quartier_intitule:
    path: /quartiers/intitules/{ville}
    defaults: { _controller: LGPUserBundle:Quartier:intitule }
    requirements:
        ville: \w+
    options:
        expose: true


# Experience professionnelle
lgp_user_prof_experience_pro_add:
    path: /experience-pro/add
    defaults: { _controller: LGPUserBundle:ExperiencePro:add }
    options:
        expose: true

lgp_user_prof_experience_pro_delete:
    path: /experience-pro/delete/{id}
    defaults: { _controller: LGPUserBundle:ExperiencePro:delete }
    requirements:
        id: \d+
    options:
        expose: true

# Diplome
lgp_user_prof_diplome_add:
    path: /diplome/add
    defaults: { _controller: LGPUserBundle:Diplome:add }

lgp_user_prof_diplome_delete:
    path: /diplome/delete/{id}
    defaults: { _controller: LGPUserBundle:Diplome:delete }
    requirements:
        id: \d+
    options:
        expose: true

# Telephone
lgp_user_telephone_add:
    path: /telephone/add
    defaults: { _controller: LGPUserBundle:Telephone:add }

lgp_user_telephone2_add:
    path: /telephone2/add
    defaults: { _controller: LGPUserBundle:Telephone:add2 }

lgp_user_telephone_confirm:
    path: /telephone/confirm
    defaults: { _controller: LGPUserBundle:Telephone:confirm }

# CV
lgp_user_prof_cv_add:
    path: /cv/add
    defaults: { _controller: LGPUserBundle:CV:add }
