lgp_reservation_homepage:
    path:     /
    defaults: { _controller: LGPReservationBundle:Default:index }
    
lgp_reservation_detail:
    path:    /detail
    defaults: { _controller: LGPReservationBundle:Reservation:detail }
    
lgp_reservation_cart:
    path:    /cart
    defaults: { _controller: LGPReservationBundle:Reservation:cart }
    
lgp_reservation_cart_add:
    path:    /cart/add
    defaults: { _controller: LGPReservationBundle:Reservation:addCart }
 
lgp_reservation_cart_remove:
    path:    /cart/remove/{key}
    defaults: { _controller: LGPReservationBundle:Reservation:removeCart }

