# routing for reservation
lgp_reservation_homepage:
    path:     /
    defaults: { _controller: LGPReservationBundle:Default:index }
    
lgp_reservation_detail:
    path:    /detail/{id}
    defaults: { _controller: LGPReservationBundle:Reservation:detail }
    requirements:
        id: \d+
   
lgp_reservation_confirm:
    path:    /cart/confirm/{userId}
    defaults: { _controller: LGPReservationBundle:Reservation:confirmReservation }
    requirements:
        userId: \d+ 

lgp_reservation_paiement:
    path:    /paiement
    defaults: { _controller: LGPReservationBundle:Reservation:paiementMode }
    requirements:
        userId: \d+


# routing for cart
lgp_reservation_cart:
    path:    /cart
    defaults: { _controller: LGPReservationBundle:Cart:cart }
    
lgp_reservation_cart_add:
    path:    /cart/add/{profId}
    defaults: { _controller: LGPReservationBundle:Cart:addCart }
    requirements:
        profId: \d+
    options:
        expose: true
 
lgp_reservation_cart_remove:
    path:    /cart/remove/{key}
    defaults: { _controller: LGPReservationBundle:Cart:removeCart }
