<?php

namespace Proxies\__CG__\LGP\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Prof extends \LGP\UserBundle\Entity\Prof implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'user', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'id', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'ville', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'quartier', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'boitePostale', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'situationMatrimoniale', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'niveauScolaire', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'nombreEnfants', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'isRecommande', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'isActif', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'presentation', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'profession'];
        }

        return ['__isInitialized__', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'user', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'id', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'ville', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'quartier', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'boitePostale', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'situationMatrimoniale', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'niveauScolaire', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'nombreEnfants', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'isRecommande', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'isActif', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'presentation', '' . "\0" . 'LGP\\UserBundle\\Entity\\Prof' . "\0" . 'profession'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Prof $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuartier($quartier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuartier', [$quartier]);

        return parent::setQuartier($quartier);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuartier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuartier', []);

        return parent::getQuartier();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoitePostale($boitePostale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoitePostale', [$boitePostale]);

        return parent::setBoitePostale($boitePostale);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoitePostale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoitePostale', []);

        return parent::getBoitePostale();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituationMatrimoniale($situationMatrimoniale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituationMatrimoniale', [$situationMatrimoniale]);

        return parent::setSituationMatrimoniale($situationMatrimoniale);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituationMatrimoniale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituationMatrimoniale', []);

        return parent::getSituationMatrimoniale();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveauScolaire($niveauScolaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveauScolaire', [$niveauScolaire]);

        return parent::setNiveauScolaire($niveauScolaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveauScolaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveauScolaire', []);

        return parent::getNiveauScolaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreEnfants($nombreEnfants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreEnfants', [$nombreEnfants]);

        return parent::setNombreEnfants($nombreEnfants);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreEnfants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreEnfants', []);

        return parent::getNombreEnfants();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRecommande($isRecommande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRecommande', [$isRecommande]);

        return parent::setIsRecommande($isRecommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRecommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRecommande', []);

        return parent::getIsRecommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActif($isActif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActif', [$isActif]);

        return parent::setIsActif($isActif);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActif', []);

        return parent::getIsActif();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresentation($presentation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresentation', [$presentation]);

        return parent::setPresentation($presentation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresentation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresentation', []);

        return parent::getPresentation();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfession($profession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfession', [$profession]);

        return parent::setProfession($profession);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfession', []);

        return parent::getProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\LGP\UserBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

}
