<?php

namespace Proxies\__CG__\LGP\ReservationBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ReservationEnseignement extends \LGP\ReservationBundle\Entity\ReservationEnseignement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'id', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'lieuDeCours', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'dateDebut', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'nbApprenants', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'ville', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'quartier', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'isFinish', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'joursDeCours', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'programmeDeCours', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'reservation', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'enseignement', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'evaluations', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'seancesDeCours'];
        }

        return ['__isInitialized__', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'id', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'lieuDeCours', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'dateDebut', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'nbApprenants', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'ville', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'quartier', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'isFinish', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'joursDeCours', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'programmeDeCours', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'reservation', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'enseignement', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'evaluations', '' . "\0" . 'LGP\\ReservationBundle\\Entity\\ReservationEnseignement' . "\0" . 'seancesDeCours'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ReservationEnseignement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuDeCours($lieuDeCours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuDeCours', [$lieuDeCours]);

        return parent::setLieuDeCours($lieuDeCours);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuDeCours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuDeCours', []);

        return parent::getLieuDeCours();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut($dateDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', [$dateDebut]);

        return parent::setDateDebut($dateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', []);

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbApprenants($nbApprenants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbApprenants', [$nbApprenants]);

        return parent::setNbApprenants($nbApprenants);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbApprenants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbApprenants', []);

        return parent::getNbApprenants();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuartier($quartier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuartier', [$quartier]);

        return parent::setQuartier($quartier);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuartier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuartier', []);

        return parent::getQuartier();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsFinish($isFinish)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsFinish', [$isFinish]);

        return parent::setIsFinish($isFinish);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsFinish()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsFinish', []);

        return parent::getIsFinish();
    }

    /**
     * {@inheritDoc}
     */
    public function addJoursDeCour(\LGP\ReservationBundle\Entity\JourDeCours $joursDeCour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJoursDeCour', [$joursDeCour]);

        return parent::addJoursDeCour($joursDeCour);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJoursDeCour(\LGP\ReservationBundle\Entity\JourDeCours $joursDeCour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJoursDeCour', [$joursDeCour]);

        return parent::removeJoursDeCour($joursDeCour);
    }

    /**
     * {@inheritDoc}
     */
    public function getJoursDeCours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJoursDeCours', []);

        return parent::getJoursDeCours();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgrammeDeCours(\LGP\CourseBundle\Entity\ProgrammeDeCours $programmeDeCours = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgrammeDeCours', [$programmeDeCours]);

        return parent::setProgrammeDeCours($programmeDeCours);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgrammeDeCours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgrammeDeCours', []);

        return parent::getProgrammeDeCours();
    }

    /**
     * {@inheritDoc}
     */
    public function setReservation(\LGP\ReservationBundle\Entity\Reservation $reservation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReservation', [$reservation]);

        return parent::setReservation($reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservation', []);

        return parent::getReservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnseignement(\LGP\CourseBundle\Entity\Enseignement $enseignement = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnseignement', [$enseignement]);

        return parent::setEnseignement($enseignement);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnseignement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnseignement', []);

        return parent::getEnseignement();
    }

    /**
     * {@inheritDoc}
     */
    public function addSeancesDeCour(\LGP\CourseBundle\Entity\SeanceDeCours $seancesDeCour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSeancesDeCour', [$seancesDeCour]);

        return parent::addSeancesDeCour($seancesDeCour);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSeancesDeCour(\LGP\CourseBundle\Entity\SeanceDeCours $seancesDeCour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSeancesDeCour', [$seancesDeCour]);

        return parent::removeSeancesDeCour($seancesDeCour);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeancesDeCours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeancesDeCours', []);

        return parent::getSeancesDeCours();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvaluation(\LGP\CourseBundle\Entity\Evaluation $evaluation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvaluation', [$evaluation]);

        return parent::addEvaluation($evaluation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvaluation(\LGP\CourseBundle\Entity\Evaluation $evaluation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvaluation', [$evaluation]);

        return parent::removeEvaluation($evaluation);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluations', []);

        return parent::getEvaluations();
    }

}
